# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql_monitor',
            name='table_check',
            field=models.SmallIntegerField(default=0),
        ),
    ]
