# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('port', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('finish_date', models.DateTimeField(null=True)),
                ('master_log_file', models.CharField(max_length=50, null=True)),
                ('master_log_pos', models.CharField(max_length=30, null=True)),
                ('backup_local_path', models.CharField(max_length=200, null=True)),
                ('backup_files', models.CharField(max_length=2000, null=True)),
                ('is_tar', models.BooleanField(default=False)),
                ('local_tar_file', models.CharField(max_length=300)),
                ('backup_remote_path', models.CharField(max_length=200, null=True)),
                ('remote_tar_file', models.CharField(max_length=200, null=True)),
                ('verify', models.BooleanField(default=False)),
                ('verify_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HOST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=200)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestoreLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_created=True, verbose_name='start datetime')),
                ('hostname', models.CharField(db_index=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('port', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=50, null=True, verbose_name='Restore type:FULL,INC,BINLOG,DUMP')),
                ('restore_ip', models.GenericIPAddressField(verbose_name='resotre server ip')),
                ('restore_file', models.CharField(max_length=3000, verbose_name='restore files ')),
                ('restore_endpos', models.CharField(max_length=300, verbose_name='end of resotre datetime or binlog file pos')),
                ('end_date', models.DateTimeField(verbose_name='start datetime')),
                ('spend_time', models.IntegerField(verbose_name='spend time mi')),
                ('local_path', models.CharField(max_length=500, verbose_name='local path for backup saved')),
                ('remote_path', models.CharField(max_length=500, verbose_name='remote path from  backup saved')),
                ('remote_ip', models.GenericIPAddressField(verbose_name='remote storage server ip ')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bkrs.HOST')),
            ],
        ),
        migrations.AddField(
            model_name='backuplog',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bkrs.HOST'),
        ),
    ]
