# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mysql_monitor_table_check'),
        ('bkrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='backfailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.CharField(max_length=50, null=True)),
                ('customer_name', models.CharField(max_length=50, null=True)),
                ('back_success', models.CharField(max_length=50, null=True)),
                ('back_failed', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupHostConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_backup_dir', models.CharField(max_length=50)),
                ('xtrabackup', models.NullBooleanField()),
                ('xtrabackup_conf', models.CharField(max_length=200, null=True)),
                ('xtrabackup_task', models.CharField(max_length=50, null=True)),
                ('mysqldump', models.NullBooleanField()),
                ('mysqldump_conf', models.CharField(max_length=200, null=True)),
                ('mysqldump_task', models.CharField(max_length=50, null=True)),
                ('binlog', models.NullBooleanField()),
                ('binlog_conf', models.CharField(max_length=200, null=True)),
                ('binlog_task', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=50)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=200)),
                ('regdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='count_day_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.CharField(max_length=50, null=True)),
                ('back_file_success', models.BooleanField(default=False)),
                ('back_customers_success', models.BooleanField(default=False)),
                ('back_file_failed', models.BooleanField(default=False)),
                ('back_customers_failed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='count_mon_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateTimeField(null=True)),
                ('back_customers', models.BooleanField(default=False)),
                ('back_customers_stop', models.BooleanField(default=False)),
                ('back_file', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='backuplog',
            old_name='backup_remote_path',
            new_name='local_tar_file_md5',
        ),
        migrations.AddField(
            model_name='backuplog',
            name='backup_files_size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='remote_backup_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Db_instance'),
        ),
        migrations.AlterField(
            model_name='restorelog',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Db_instance'),
        ),
        migrations.DeleteModel(
            name='HOST',
        ),
        migrations.AddField(
            model_name='backuphostconf',
            name='backup_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bkrs.BackupServer'),
        ),
        migrations.AddField(
            model_name='backuphostconf',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Db_instance'),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='remote_backup_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bkrs.BackupServer'),
        ),
    ]
