# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mysql_monitor_table_check'),
        ('bkrs', '0002_auto_20180130_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backfailed',
            old_name='customer_name',
            new_name='back_type',
        ),
        migrations.AddField(
            model_name='backfailed',
            name='error',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='backfailed',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Db_instance'),
        ),
        migrations.AddField(
            model_name='backfailed',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='backfailed',
            name='port',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='backuphostconf',
            name='customers_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backuphostconf',
            name='customers_short',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backuphostconf',
            name='dbname',
            field=models.CharField(default='ALL', max_length=80),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='binlog_max_datetime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='binlog_max_pos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='binlog_min_datetime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='binlog_min_pos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='backuphostconf',
            name='local_backup_dir',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='backupserver',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
