# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkrs', '0004_auto_20180211_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplog',
            name='finish_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='start_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
